
name: Hello GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "👋 Hello from GitHub Actions on ${{ github.event_name }}"
      - name: step 2
        run: echo "${{ github.repository }}"
      - name: step 3
        run: echo "${{ github.actor }}"
      - name: step 4
        run: echo "${{ github.ref }}"