
name: Hello GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "👋 Hello from GitHub Actions on ${{ github.event_name }}"
      - name: Print GitHub Info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
  
  use-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

  demo-env:
    needs: say_hello
    runs-on: ubuntu-latest
    env:
      NAME: "Ankur"
    
    steps:
      - name: Greet
        run: echo "Hi $NAME"