
name: Hello GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "👋 Hello from GitHub Actions on ${{ github.event_name }}"