
name: Hello GitHub Actions

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "👋 Hello from GitHub Actions!"